### ISSUE TITLE
Several automated reports of failure to download ffmpeg

### ISSUE THREAD

**Issue by smathot** [dschreij/opensesame-plugin-mediaplayer#3]
I regularly get automated bug reports like the one below, indicating that some part of ffmpeg cannot be downloaded. This particular error is from Mac OS, but analogous errors come from Windows. Do you think it's indeed an internet connection issue? If so, then it's not really a bug, and we can close the issue again. But that actually seems unlikely, because the automated bug reports also require an internet connection!

``` .python
Traceback (most recent call last):
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 753, in dropEvent
    self.drop_event_item_new(data, e)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 672, in drop_event_item_new
    item, new_items = self.drop_get_item_snippet(data)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 560, in drop_get_item_snippet
    catch_exceptions=False)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libqtopensesame/misc/qtitem_store.py", line 105, in new
    script=script)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/item_store.py", line 162, in new
    u"Failed to load plugin '%s'" % _type, exception=e)
osexception: 
Failed to load plugin 'media_player_mpy'

item-stack: 
exception message: Unable to download 'ffmpeg.osx'. Perhaps there is a no internet connection? If there is, please report this problem.
time: Mon Aug 15 14:13:33 2016
exception type: IOError

Traceback:
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/item_store.py", line 159, in new
    self.experiment, script, self.experiment.item_prefix())
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/plugins.py", line 361, in load_plugin
    item_module = import_plugin(plugin, _type=_type)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/libopensesame/plugins.py", line 332, in import_plugin
    return imp.load_source(plugin, path)
  File "/Applications/OpenSesame.app/Contents/Resources/share/opensesame_plugins/media_player_mpy/media_player_mpy.py", line 42, in <module>
    import mediadecoder
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/mediadecoder/__init__.py", line 6, in <module>
    from mediadecoder.decoder import Decoder
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/mediadecoder/decoder.py", line 9, in <module>
    from moviepy.video.io.VideoFileClip import VideoFileClip
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 52, in get_exe
    exe = get_remote_file('ffmpeg/' + FNAME_PER_PLATFORM[plat])
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/imageio/core/fetching.py", line 98, in get_remote_file
    _fetch_file(url, filename)
  File "/Applications/OpenSesame.app/Contents/Resources/lib/python2.7/site-packages/imageio/core/fetching.py", line 154, in _fetch_file
    os.path.basename(file_name))
IOError: Unable to download 'ffmpeg.osx'. Perhaps there is a no internet connection? If there is, please report this problem.
```

**Comment by dschreij** [comment]
It could be that the server containing the ffmpeg library is temporarily unreachable, so it doesn't need be a problem with the Internet connection on the client's side. I've had similar problems like this when building packages for conda, when the automated build script tries to download the source files. Incidentally these downloads fail, but if I try again directly afterwards the download just works perfectly again. I guess sometimes the system serving the ffmpeg library can handle all requests and then a download fails.

I still think the best solution to this problem would be to include the ffmpeg library in the OpenSesame package so it doesn't need to be separately downloaded. I hope to look at this in the near future.

**Comment by smathot** [comment]
You're probably right. So let's close this issue, and keep the idea of bundling ffmpeg in mind.
