### ISSUE TITLE
Incompatibility with OpenSesame 3.3

### ISSUE THREAD

**Issue by dschreij** [dschreij/opensesame-plugin-mediaplayer#7]
When trying to drag the media_player_mpy package to the OpenSesame overview window, the following stacktrace is shown:
```python
Traceback (most recent call last):
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/share/opensesame_plugins/media_player_mpy/media_player_mpy.py", line 312, in __init__
    self.play_audio.currentTextChanged.connect(self.set_soundrenderer_status)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item.py", line 241, in __getattr__
    raise AttributeError(u'%s not found' % var)
AttributeError: play_audio not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item_store.py", line 190, in new
    self.experiment.item_prefix()
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/plugins.py", line 449, in load_plugin
    item = item_class(item_name, experiment, string)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/share/opensesame_plugins/media_player_mpy/media_player_mpy.py", line 314, in __init__
    self.play_audio.editTextChanged.connect(self.set_soundrenderer_status)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item.py", line 241, in __getattr__
    raise AttributeError(u'%s not found' % var)
AttributeError: play_audio not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 788, in dropEvent
    self.drop_event_item_new(data, e)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 702, in drop_event_item_new
    item, new_items = self.drop_get_item_snippet(data)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libqtopensesame/widgets/tree_overview.py", line 588, in drop_get_item_snippet
    catch_exceptions=False)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libqtopensesame/misc/qtitem_store.py", line 118, in new
    allow_rename=allow_rename
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item_store.py", line 195, in new
    exception=e
libopensesame.exceptions.osexception: 
Failed to load plugin 'media_player_mpy'
item-stack: 
time: Fri Apr 24 19:30:59 2020
exception type: AttributeError
exception message: play_audio not found
Traceback:
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/share/opensesame_plugins/media_player_mpy/media_player_mpy.py", line 312, in __init__
    self.play_audio.currentTextChanged.connect(self.set_soundrenderer_status)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item.py", line 241, in __getattr__
    raise AttributeError(u'%s not found' % var)
AttributeError: play_audio not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item_store.py", line 190, in new
    self.experiment.item_prefix()
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/plugins.py", line 449, in load_plugin
    item = item_class(item_name, experiment, string)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/share/opensesame_plugins/media_player_mpy/media_player_mpy.py", line 314, in __init__
    self.play_audio.editTextChanged.connect(self.set_soundrenderer_status)
  File "/Users/intankwardhani/anaconda3/envs/opensesame_py3/lib/python3.7/site-packages/libopensesame/item.py", line 241, in __getattr__
    raise AttributeError(u'%s not found' % var)
AttributeError: play_audio not found
```

**Comment by dschreij** [comment]
Fixed by #8
